/** Regenerate the vendored Codex app-server TypeScript protocol bindings. */
import { execFileSync } from "node:child_process";
import { readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const codex = resolve(root, "sdk/node_modules/.bin/codex");
const biome = resolve(root, "sdk/node_modules/.bin/biome");
const out = resolve(root, "sdk/src/codex/protocol/generated");
const versionOutput = execFileSync(codex, ["--version"], { encoding: "utf8" }).trim();
const version = versionOutput.replace(/^codex-cli\s+/, "");

if (!version.startsWith("0.144.")) {
  throw new Error(`Expected Codex CLI 0.144.x, received ${versionOutput}`);
}

rmSync(out, { recursive: true, force: true });
execFileSync(codex, ["app-server", "generate-ts", "--out", out], { stdio: "inherit" });
execFileSync(biome, ["check", "--write", out], { stdio: "inherit" });

const indexPath = resolve(out, "index.ts");
const generated = readFileSync(indexPath, "utf8");
const date = new Date().toISOString().slice(0, 10);
const provenance =
  `// Generated by @openai/codex CLI ${version} (\`codex app-server generate-ts\`) on ${date}.\n` +
  "// Source: openai/codex, codex-rs/app-server-protocol/schema/json.\n";
writeFileSync(indexPath, provenance + generated);
